/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as StudentRouteImport } from './routes/student'
import { Route as PublicRouteImport } from './routes/public'
import { Route as MentorRouteImport } from './routes/mentor'
import { Route as HelpRouteImport } from './routes/help'
import { Route as FeedbackRouteImport } from './routes/feedback'
import { Route as CoverRouteImport } from './routes/cover'
import { Route as IndexRouteImport } from './routes/index'
import { Route as StudentIndexRouteImport } from './routes/student.index'
import { Route as MentorIndexRouteImport } from './routes/mentor.index'
import { Route as StudentCreateRouteImport } from './routes/student.create'
import { Route as MentorCreateRouteImport } from './routes/mentor.create'
import { Route as StudentPublicIndexRouteImport } from './routes/student.public.index'
import { Route as StudentCreateIndexRouteImport } from './routes/student.create.index'
import { Route as MentorCreateIndexRouteImport } from './routes/mentor.create.index'
import { Route as StudentPublicMentorIdRouteImport } from './routes/student.public.$mentorId'
import { Route as StudentCreateResumeRouteImport } from './routes/student.create.resume'
import { Route as StudentCreateAspirationRouteImport } from './routes/student.create.aspiration'
import { Route as MentorCreatePostRouteImport } from './routes/mentor.create.post'
import { Route as MentorCreateInfoRouteImport } from './routes/mentor.create.info'

const StudentRoute = StudentRouteImport.update({
  id: '/student',
  path: '/student',
  getParentRoute: () => rootRouteImport,
} as any)
const PublicRoute = PublicRouteImport.update({
  id: '/public',
  path: '/public',
  getParentRoute: () => rootRouteImport,
} as any)
const MentorRoute = MentorRouteImport.update({
  id: '/mentor',
  path: '/mentor',
  getParentRoute: () => rootRouteImport,
} as any)
const HelpRoute = HelpRouteImport.update({
  id: '/help',
  path: '/help',
  getParentRoute: () => rootRouteImport,
} as any)
const FeedbackRoute = FeedbackRouteImport.update({
  id: '/feedback',
  path: '/feedback',
  getParentRoute: () => rootRouteImport,
} as any)
const CoverRoute = CoverRouteImport.update({
  id: '/cover',
  path: '/cover',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const StudentIndexRoute = StudentIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => StudentRoute,
} as any)
const MentorIndexRoute = MentorIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => MentorRoute,
} as any)
const StudentCreateRoute = StudentCreateRouteImport.update({
  id: '/create',
  path: '/create',
  getParentRoute: () => StudentRoute,
} as any)
const MentorCreateRoute = MentorCreateRouteImport.update({
  id: '/create',
  path: '/create',
  getParentRoute: () => MentorRoute,
} as any)
const StudentPublicIndexRoute = StudentPublicIndexRouteImport.update({
  id: '/public/',
  path: '/public/',
  getParentRoute: () => StudentRoute,
} as any)
const StudentCreateIndexRoute = StudentCreateIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => StudentCreateRoute,
} as any)
const MentorCreateIndexRoute = MentorCreateIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => MentorCreateRoute,
} as any)
const StudentPublicMentorIdRoute = StudentPublicMentorIdRouteImport.update({
  id: '/public/$mentorId',
  path: '/public/$mentorId',
  getParentRoute: () => StudentRoute,
} as any)
const StudentCreateResumeRoute = StudentCreateResumeRouteImport.update({
  id: '/resume',
  path: '/resume',
  getParentRoute: () => StudentCreateRoute,
} as any)
const StudentCreateAspirationRoute = StudentCreateAspirationRouteImport.update({
  id: '/aspiration',
  path: '/aspiration',
  getParentRoute: () => StudentCreateRoute,
} as any)
const MentorCreatePostRoute = MentorCreatePostRouteImport.update({
  id: '/post',
  path: '/post',
  getParentRoute: () => MentorCreateRoute,
} as any)
const MentorCreateInfoRoute = MentorCreateInfoRouteImport.update({
  id: '/info',
  path: '/info',
  getParentRoute: () => MentorCreateRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/cover': typeof CoverRoute
  '/feedback': typeof FeedbackRoute
  '/help': typeof HelpRoute
  '/mentor': typeof MentorRouteWithChildren
  '/public': typeof PublicRoute
  '/student': typeof StudentRouteWithChildren
  '/mentor/create': typeof MentorCreateRouteWithChildren
  '/student/create': typeof StudentCreateRouteWithChildren
  '/mentor/': typeof MentorIndexRoute
  '/student/': typeof StudentIndexRoute
  '/mentor/create/info': typeof MentorCreateInfoRoute
  '/mentor/create/post': typeof MentorCreatePostRoute
  '/student/create/aspiration': typeof StudentCreateAspirationRoute
  '/student/create/resume': typeof StudentCreateResumeRoute
  '/student/public/$mentorId': typeof StudentPublicMentorIdRoute
  '/mentor/create/': typeof MentorCreateIndexRoute
  '/student/create/': typeof StudentCreateIndexRoute
  '/student/public/': typeof StudentPublicIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/cover': typeof CoverRoute
  '/feedback': typeof FeedbackRoute
  '/help': typeof HelpRoute
  '/public': typeof PublicRoute
  '/mentor': typeof MentorIndexRoute
  '/student': typeof StudentIndexRoute
  '/mentor/create/info': typeof MentorCreateInfoRoute
  '/mentor/create/post': typeof MentorCreatePostRoute
  '/student/create/aspiration': typeof StudentCreateAspirationRoute
  '/student/create/resume': typeof StudentCreateResumeRoute
  '/student/public/$mentorId': typeof StudentPublicMentorIdRoute
  '/mentor/create': typeof MentorCreateIndexRoute
  '/student/create': typeof StudentCreateIndexRoute
  '/student/public': typeof StudentPublicIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/cover': typeof CoverRoute
  '/feedback': typeof FeedbackRoute
  '/help': typeof HelpRoute
  '/mentor': typeof MentorRouteWithChildren
  '/public': typeof PublicRoute
  '/student': typeof StudentRouteWithChildren
  '/mentor/create': typeof MentorCreateRouteWithChildren
  '/student/create': typeof StudentCreateRouteWithChildren
  '/mentor/': typeof MentorIndexRoute
  '/student/': typeof StudentIndexRoute
  '/mentor/create/info': typeof MentorCreateInfoRoute
  '/mentor/create/post': typeof MentorCreatePostRoute
  '/student/create/aspiration': typeof StudentCreateAspirationRoute
  '/student/create/resume': typeof StudentCreateResumeRoute
  '/student/public/$mentorId': typeof StudentPublicMentorIdRoute
  '/mentor/create/': typeof MentorCreateIndexRoute
  '/student/create/': typeof StudentCreateIndexRoute
  '/student/public/': typeof StudentPublicIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/cover'
    | '/feedback'
    | '/help'
    | '/mentor'
    | '/public'
    | '/student'
    | '/mentor/create'
    | '/student/create'
    | '/mentor/'
    | '/student/'
    | '/mentor/create/info'
    | '/mentor/create/post'
    | '/student/create/aspiration'
    | '/student/create/resume'
    | '/student/public/$mentorId'
    | '/mentor/create/'
    | '/student/create/'
    | '/student/public/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/cover'
    | '/feedback'
    | '/help'
    | '/public'
    | '/mentor'
    | '/student'
    | '/mentor/create/info'
    | '/mentor/create/post'
    | '/student/create/aspiration'
    | '/student/create/resume'
    | '/student/public/$mentorId'
    | '/mentor/create'
    | '/student/create'
    | '/student/public'
  id:
    | '__root__'
    | '/'
    | '/cover'
    | '/feedback'
    | '/help'
    | '/mentor'
    | '/public'
    | '/student'
    | '/mentor/create'
    | '/student/create'
    | '/mentor/'
    | '/student/'
    | '/mentor/create/info'
    | '/mentor/create/post'
    | '/student/create/aspiration'
    | '/student/create/resume'
    | '/student/public/$mentorId'
    | '/mentor/create/'
    | '/student/create/'
    | '/student/public/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CoverRoute: typeof CoverRoute
  FeedbackRoute: typeof FeedbackRoute
  HelpRoute: typeof HelpRoute
  MentorRoute: typeof MentorRouteWithChildren
  PublicRoute: typeof PublicRoute
  StudentRoute: typeof StudentRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/student': {
      id: '/student'
      path: '/student'
      fullPath: '/student'
      preLoaderRoute: typeof StudentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/public': {
      id: '/public'
      path: '/public'
      fullPath: '/public'
      preLoaderRoute: typeof PublicRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mentor': {
      id: '/mentor'
      path: '/mentor'
      fullPath: '/mentor'
      preLoaderRoute: typeof MentorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/help': {
      id: '/help'
      path: '/help'
      fullPath: '/help'
      preLoaderRoute: typeof HelpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/feedback': {
      id: '/feedback'
      path: '/feedback'
      fullPath: '/feedback'
      preLoaderRoute: typeof FeedbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cover': {
      id: '/cover'
      path: '/cover'
      fullPath: '/cover'
      preLoaderRoute: typeof CoverRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/student/': {
      id: '/student/'
      path: '/'
      fullPath: '/student/'
      preLoaderRoute: typeof StudentIndexRouteImport
      parentRoute: typeof StudentRoute
    }
    '/mentor/': {
      id: '/mentor/'
      path: '/'
      fullPath: '/mentor/'
      preLoaderRoute: typeof MentorIndexRouteImport
      parentRoute: typeof MentorRoute
    }
    '/student/create': {
      id: '/student/create'
      path: '/create'
      fullPath: '/student/create'
      preLoaderRoute: typeof StudentCreateRouteImport
      parentRoute: typeof StudentRoute
    }
    '/mentor/create': {
      id: '/mentor/create'
      path: '/create'
      fullPath: '/mentor/create'
      preLoaderRoute: typeof MentorCreateRouteImport
      parentRoute: typeof MentorRoute
    }
    '/student/public/': {
      id: '/student/public/'
      path: '/public'
      fullPath: '/student/public/'
      preLoaderRoute: typeof StudentPublicIndexRouteImport
      parentRoute: typeof StudentRoute
    }
    '/student/create/': {
      id: '/student/create/'
      path: '/'
      fullPath: '/student/create/'
      preLoaderRoute: typeof StudentCreateIndexRouteImport
      parentRoute: typeof StudentCreateRoute
    }
    '/mentor/create/': {
      id: '/mentor/create/'
      path: '/'
      fullPath: '/mentor/create/'
      preLoaderRoute: typeof MentorCreateIndexRouteImport
      parentRoute: typeof MentorCreateRoute
    }
    '/student/public/$mentorId': {
      id: '/student/public/$mentorId'
      path: '/public/$mentorId'
      fullPath: '/student/public/$mentorId'
      preLoaderRoute: typeof StudentPublicMentorIdRouteImport
      parentRoute: typeof StudentRoute
    }
    '/student/create/resume': {
      id: '/student/create/resume'
      path: '/resume'
      fullPath: '/student/create/resume'
      preLoaderRoute: typeof StudentCreateResumeRouteImport
      parentRoute: typeof StudentCreateRoute
    }
    '/student/create/aspiration': {
      id: '/student/create/aspiration'
      path: '/aspiration'
      fullPath: '/student/create/aspiration'
      preLoaderRoute: typeof StudentCreateAspirationRouteImport
      parentRoute: typeof StudentCreateRoute
    }
    '/mentor/create/post': {
      id: '/mentor/create/post'
      path: '/post'
      fullPath: '/mentor/create/post'
      preLoaderRoute: typeof MentorCreatePostRouteImport
      parentRoute: typeof MentorCreateRoute
    }
    '/mentor/create/info': {
      id: '/mentor/create/info'
      path: '/info'
      fullPath: '/mentor/create/info'
      preLoaderRoute: typeof MentorCreateInfoRouteImport
      parentRoute: typeof MentorCreateRoute
    }
  }
}

interface MentorCreateRouteChildren {
  MentorCreateInfoRoute: typeof MentorCreateInfoRoute
  MentorCreatePostRoute: typeof MentorCreatePostRoute
  MentorCreateIndexRoute: typeof MentorCreateIndexRoute
}

const MentorCreateRouteChildren: MentorCreateRouteChildren = {
  MentorCreateInfoRoute: MentorCreateInfoRoute,
  MentorCreatePostRoute: MentorCreatePostRoute,
  MentorCreateIndexRoute: MentorCreateIndexRoute,
}

const MentorCreateRouteWithChildren = MentorCreateRoute._addFileChildren(
  MentorCreateRouteChildren,
)

interface MentorRouteChildren {
  MentorCreateRoute: typeof MentorCreateRouteWithChildren
  MentorIndexRoute: typeof MentorIndexRoute
}

const MentorRouteChildren: MentorRouteChildren = {
  MentorCreateRoute: MentorCreateRouteWithChildren,
  MentorIndexRoute: MentorIndexRoute,
}

const MentorRouteWithChildren =
  MentorRoute._addFileChildren(MentorRouteChildren)

interface StudentCreateRouteChildren {
  StudentCreateAspirationRoute: typeof StudentCreateAspirationRoute
  StudentCreateResumeRoute: typeof StudentCreateResumeRoute
  StudentCreateIndexRoute: typeof StudentCreateIndexRoute
}

const StudentCreateRouteChildren: StudentCreateRouteChildren = {
  StudentCreateAspirationRoute: StudentCreateAspirationRoute,
  StudentCreateResumeRoute: StudentCreateResumeRoute,
  StudentCreateIndexRoute: StudentCreateIndexRoute,
}

const StudentCreateRouteWithChildren = StudentCreateRoute._addFileChildren(
  StudentCreateRouteChildren,
)

interface StudentRouteChildren {
  StudentCreateRoute: typeof StudentCreateRouteWithChildren
  StudentIndexRoute: typeof StudentIndexRoute
  StudentPublicMentorIdRoute: typeof StudentPublicMentorIdRoute
  StudentPublicIndexRoute: typeof StudentPublicIndexRoute
}

const StudentRouteChildren: StudentRouteChildren = {
  StudentCreateRoute: StudentCreateRouteWithChildren,
  StudentIndexRoute: StudentIndexRoute,
  StudentPublicMentorIdRoute: StudentPublicMentorIdRoute,
  StudentPublicIndexRoute: StudentPublicIndexRoute,
}

const StudentRouteWithChildren =
  StudentRoute._addFileChildren(StudentRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CoverRoute: CoverRoute,
  FeedbackRoute: FeedbackRoute,
  HelpRoute: HelpRoute,
  MentorRoute: MentorRouteWithChildren,
  PublicRoute: PublicRoute,
  StudentRoute: StudentRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
